name: Setup

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DB: ullebets_unibet
      SOURCE_MONGODB_DB: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --no-audit --no-fund
      - run: npm run healthcheck
      - run: npm run indexes
      - run: npm run source:scan
